site_name: Python AsyncAPI
site_description: |
  Python library for translate asyncapi specification to python code,
  without code generation.

theme:
    name: material
    custom_dir: theme
    palette:
      primary: deep-purple
      accent: grey
    logo: asyncapi-python-logo.svg
    favicon: asyncapi-python-favicon.svg

repo_name: dutradda/asyncapi-python
repo_url: https://github.com/dutradda/asyncapi-python
edit_uri: ''

nav:
    - Home: index.md
    - Declaring Specification: auto-spec.md
    - Expose Docs: expose-docs.md
    - Google PubSub Tutorial:
      - HTTP Specification: gcloud-pubsub/http-specification.md
      - Python Specification: gcloud-pubsub/python-specification.md
    - Development - Contributing: contributing.md
    - Changelog: changelog.md

markdown_extensions:
    - markdown_include.include:
        base_path: docs
    - codehilite:
        guess_lang: false

extra_css:
  - stylesheets/dark_theme.css
  - stylesheets/codehilite.css
